language: node_js
node_js:
  - node
  - iojs
  - "4.2"
  - "4.1"
  - "4.0"
  - "3"
  - "2"
  - "1.8"
  - "1.0"
  - "0.12"
  - "0.11"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
